metadata:
- appName: ''
  dataId: application.yml
  desc: ''
  group: jeesite-cloud-yml
  type: yaml
- appName: ''
  dataId: application-prod.yml
  group: jeesite-cloud-yml
  type: yaml
- appName: ''
  dataId: application-test.yml
  group: jeesite-cloud-yml
  type: yaml
- appName: ''
  dataId: jeesite-cloud-gateway.yml
  desc: ''
  group: jeesite-cloud-yml
  type: yaml
- appName: ''
  dataId: jeesite-cloud-module-core.yml
  group: jeesite-cloud-yml
  type: yaml
- appName: ''
  dataId: jeesite-cloud-module-files.yml
  group: jeesite-cloud-yml
  type: yaml
- appName: ''
  dataId: jeesite-cloud-module-msg.yml
  group: jeesite-cloud-yml
  type: yaml
- appName: ''
  dataId: jeesite-cloud-module-test1.yml
  group: jeesite-cloud-yml
  type: yaml
- appName: ''
  dataId: jeesite-cloud-module-test2.yml
  group: jeesite-cloud-yml
  type: yaml
- appName: ''
  dataId: jeesite-cloud-module-test3.yml
  group: jeesite-cloud-yml
  type: yaml
