
#======================================#
#========== Server settings ===========#
#======================================#

server:

  port: 8981
    
#======================================#
#========== Cloud settings ============#
#======================================#

# 服务注册
eureka:

  # 实例设置
  instance:
    # 实例主机名称
    hostname: ${LOCAL_HOST:127.0.0.1}
    # 实例是否允许使用IP
    preferIpAddress: false

  # 客户端设置
  client:
    # 注册中心地址（集群时指定另外一个注册中心地址）
    serviceUrl:
      defaultZone: http://${EUREKA_HOST:127.0.0.1}:${EUREKA_PORT:8970}/eureka/
