
#======================================#
#========== Spring settings ===========#
#======================================#

spring:

  # 应用程序名称
  application:
    name: jeesite-cloud-zipkin

  # 当前环境名称（注意：不可设置为 test 它是单元测试专用的名称）
  profiles:
    active: default
    include: shared

# 仅监控业务
armeria:
  enableMetrics: false
