
#======================================#
#========== Spring settings ===========#
#======================================#

spring:

  # 应用程序名称
  application:
    name: jeesite-cloud-zipkin

  # 当前环境名称，支持 JVM 参数设置，如: -Dspring.profiles.active=prod
  profiles:
    active: default
    include: shared

# 仅监控业务
armeria:
  enableMetrics: false
