
#======================================#
#========== Server settings ===========#
#======================================#

server:

  port: 8983

#======================================#
#========== Spring settings ===========#
#======================================#

spring:

  # 应用程序名称
  application:
    name: jeesite-cloud-module-test2

  # 当前环境名称，支持 JVM 参数设置，如: -Dspring.profiles.active=prod
  profiles:
    active: default

  # 微服务组件配置
  cloud:
    
    # 服务注册和配置
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      discovery:
        namespace: ~
        group: jeesite-cloud
      config:
        namespace: ~
        group: jeesite-cloud-yml

    # 服务发现与注册优选IP前缀
    inetutils:
      preferred-networks: ${PREFERRED_NETWORKS:}

  # 加载云配置文件
  config:
    import:
      - 'nacos:application.yml'
      - 'nacos:application-${spring.profiles.active}.yml'
      - 'nacos:${spring.application.name}.yml'
      - 'nacos:${spring.application.name}-${spring.profiles.active}.yml'

  # 打印横幅
  main:
    banner-mode: "off"
    lazy-initialization: true

# 日志配置
logging:
  config: classpath:config/logback-spring.xml
