#
# Copyright (c) 2013-Now http://jeesite.com All rights reserved.
# No deletion without permission, or be held responsible to law.
# @author ThinkGem
#
# 执行 docker compose up 前，请先编译项目 mvn package
#
name: jeesite-cloud-basic

# ==================== Environment ====================
x-common-env: &common-env
  TZ: Asia/Shanghai
  LANG: C.UTF-8
  MYSQL_HOST: jeesite-mysql
  REDIS_HOST: jeesite-redis
  NACOS_HOST: jeesite-nacos

# ==================== Service Base ====================
x-service-base: &service-base
  restart: unless-stopped
  networks:
    - jeesite-cloud-network

services:

  # ==================== MySQL ====================
  jeesite-mysql:
    <<: *service-base
    container_name: jeesite-mysql
    image: docker.m.daocloud.io/mysql:8.0
    ports:
      - "13306:3306"
    environment:
      <<: *common-env
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - ./.docker/mysql/log:/var/log/mysql
      - ./.docker/mysql/data:/var/lib/mysql
      - ./.docker/mysql/conf:/etc/mysql/conf.d
      - ./nacos/db/mysql/create_user.sql:/docker-entrypoint-initdb.d/01-nacos.sql
      - ./nacos/db/mysql/nacos.sql:/docker-entrypoint-initdb.d/02-nacos.sql
      - ./modules/core/core/db/mysql/create_user.sql:/docker-entrypoint-initdb.d/03-core.sql
    command: |
      bash -c "ln -snf /usr/share/zoneinfo/$${TZ} /etc/localtime && 
      echo $${TZ} > /etc/timezone && docker-entrypoint.sh mysqld"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p123456"]
      interval: 1s
      timeout: 3s
      retries: 30

  # ==================== Redis ====================
  jeesite-redis:
    <<: *service-base
    container_name: jeesite-redis
    image: docker.m.daocloud.io/redis:7.2
    ports:
      - "16379:6379"
    environment:
      <<: *common-env
      REDISCLI_AUTH: 1234
    volumes:
      - ./.docker/redis/data:/data
    command: redis-server --requirepass 1234
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

  # ==================== Nacos ====================
  jeesite-nacos:
    <<: *service-base
    container_name: jeesite-nacos
    image: docker.m.daocloud.io/openjdk:17
    ports:
      - "18848:8848"
      - "19848:9848"
      - "18849:8849"
    environment:
      <<: *common-env
      JAVA_OPTS: -Dspring.profiles.active=prod -Dnacos.home=/nacos
    volumes:
      - ./.docker/nacos:/nacos
      - ./nacos/target:/http
    working_dir: /http
    command: |
      bash -c "if [ ! -d 'web' ]; then mkdir web && cp web.war web && cd web && jar -xvf web.war && \
      rm web.war && cd ..; fi && cd web/WEB-INF && sh startup.sh && cd WEB-INF && sh startup.sh"
    depends_on:
      jeesite-mysql:
        condition: service_healthy
      jeesite-redis:
        condition: service_healthy

# ==================== Networks ====================
networks:
  jeesite-cloud-network:
    name:  jeesite-cloud-network
    driver: bridge
