#
# Copyright (c) 2013-Now http://jeesite.com All rights reserved.
# No deletion without permission, or be held responsible to law.
# @author ThinkGem
#
# 执行 docker-compose up 前，请先编译项目 mvn package
#
name: jeesite-cloud-core

# ==================== Environment ====================
x-common-env: &common-env
  TZ: Asia/Shanghai
  LANG: C.UTF-8
  MYSQL_HOST: jeesite-cloud-mysql
  REDIS_HOST: jeesite-cloud-redis
  NACOS_HOST: jeesite-cloud-nacos

# ==================== Service Base ====================
x-service-base: &service-base
  image: docker.m.daocloud.io/eclipse-temurin:17
  environment: *common-env
  working_dir: /app
  command: >
    sh -c "if [ ! -d 'web' ]; then mkdir web && cp web.war web && cd web && jar -xvf web.war && 
    rm web.war && cd ..; fi && cd web/WEB-INF && exec sh startup.sh"
  #restart: unless-stopped
  networks:
    - jeesite-cloud-network

services:

  # ==================== Gateway ====================
  jeesite-cloud-gateway:
    <<: *service-base
    container_name: jeesite-cloud-gateway
    ports:
      - "8980:8980"
    environment:
      <<: *common-env
      JAVA_OPTS: -Dspring.profiles.active=prod -DcustomLogPath=/data
    volumes:
      - ./.docker/modules:/data
      - ./gateway/target:/app

  # ==================== Core ====================
  jeesite-cloud-core:
    <<: *service-base
    container_name: jeesite-cloud-core
    ports:
      - "8981:8981"
    environment:
      <<: *common-env
      JAVA_OPTS: >
        -Dspring.profiles.active=prod -DcustomLogPath=/data
        -Dserver.port=8981 -Djeesite.initdata=true
    volumes:
      - ./.docker/modules:/data
      - ./modules/core/core/target:/app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8981/js"]
      interval: 5s
      timeout: 5s
      retries: 60

  # ==================== Files ====================
  jeesite-cloud-files:
    <<: *service-base
    container_name: jeesite-cloud-files
    environment:
      <<: *common-env
      JAVA_OPTS: -Dspring.profiles.active=prod -DcustomLogPath=/data
    volumes:
      - ./.docker/modules:/data
      - ./modules/core/files/target:/app
    depends_on:
      jeesite-cloud-core:
        condition: service_healthy

# ==================== Networks ====================
networks:
  jeesite-cloud-network:
    name:  jeesite-cloud-network
    external: true
