
#*************** Datasource Related Configurations ***************#
## nacos.plugin.datasource.log.enabled=true
spring.sql.init.platform=sqlserver
## Count of DB:
db.num=1

## Connect URL of DB:
db.url.0=jdbc:sqlserver://127.0.0.1:1433;DatabaseName=nacos;encrypt=true;trustServerCertificate=true
db.user=nacos
db.password=nacos

### Connection pool configuration: hikariCP
db.pool.config.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
db.pool.config.connectionTestQuery=SELECT 1
db.pool.config.connectionTimeout=30000
db.pool.config.validationTimeout=10000
db.pool.config.maximumPoolSize=20
db.pool.config.minimumIdle=2

logging.level.com.alibaba.nacos=DEBUG
