
#======================================#
#========== Server settings ===========#
#======================================#

server:

  port: 9311
  servlet:
    encoding:
      force: true
      charset: UTF-8
      enabled: true

#======================================#
#========== Spring settings ===========#
#======================================#

spring:

  # 应用程序名称
  application:
    name: jeesite-cloud-sentinel

  # 当前环境名称，支持 JVM 参数设置，如: -Dspring.profiles.active=prod
  profiles:
    active: default

  # 微服务组件配置
  cloud:
    
    # 服务注册和配置
    nacos:
      server-addr: 127.0.0.1:8848
      username: nacos
      password: nacos
      discovery:
        namespace: ~
        group: jeesite-cloud
      config:
        namespace: ~
        group: jeesite-cloud-yml

    # 服务发现与注册优选IP前缀
    inetutils:
      preferred-networks: ${PREFERRED_NETWORKS:}

  # 打印横幅
  main:
    banner-mode: "off"
    lazy-initialization: false

  # MVC 映射匹配策略
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

# 日志配置
logging:
  config: classpath:config/logback-spring.xml
  level:
    org:
      springframework:
        web: info
  file:
    name: ${user.home}/logs/csp/sentinel-dashboard.log
  pattern:
    file: '%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n'

# Sentinel 配置
auth:
  username: sentinel
  password: sentinel
  filter:
    exclude-urls: /,/auth/login,/auth/logout,/registry/machine,/version,/actuator/**,/details
    exclude-url-suffixes: htm,html,js,css,map,ico,ttf,woff,png

sentinel:
  dashboard:
    version: 1.8.3

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
      
