
# 使用环境配置，只需 JVM 参数里加：-Dspring.profiles.active=prod

#======================================#
#========== Spring settings ===========#
#======================================#

spring:
  cloud:
    
    # 服务注册和配置
    nacos:
      server-addr: ${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}

    # 服务发现与注册优选IP前缀
    inetutils:
      preferred-networks: ${PREFERRED_NETWORKS:}
