
#设置与 beetl-default.properties 相同的属性将被优先加载

# v5.15.1 默认安全管理器参数，将在 v5.16.0 中更改为白名单模式 WhiteListNativeSecurityManager
#NATIVE_SECUARTY_MANAGER = com.jeesite.common.beetl.security.DefaultNativeSecurityManager

# v5.15.1 以下 IMPORT_PACKAGE_old 参数，将在 v5.16.0 中移除，移除后请进行全局替换，如下：
# 新增了一些 beetl 函数 invokeGetter、isAjaxRequest、renderResult
# 替换 @ReflectUtils.invokeGetter( 为 invokeGetter(
# 替换 @ServletUtils.isAjaxRequest( 为 isAjaxRequest(
# 替换 @ServletUtils.renderResult( 为 renderResult(
#IMPORT_PACKAGE_old=\
#	com.jeesite.common.reflect.;\
#	com.jeesite.common.security.;\
#	com.jeesite.common.web.http.;\
#	com.jeesite.common.entity.;\
#	com.jeesite.common.service.;\
#	com.jeesite.common.utils.;\

#设置导入的包名（自动合并到 IMPORT_PACKAGE 设置，键名以模块编码结尾）
#IMPORT_PACKAGE_core=\
#	com.jeesite.modules.core.utils.;\

#内置的方法
#FN.date = org.beetl.ext.fn.DateFunction

#内置的功能包
#FNP.strutil = org.beetl.ext.fn.StringUtil

#内置的格式化函数
#FT.dateFormat = com.jeesite.common.beetl.ext.format.DateFormat

#内置的默认格式化函数
#FTC.java.util.Date = com.jeesite.common.beetl.ext.format.DateFormat

#标签类
#TAG.include= org.beetl.ext.tag.IncludeTag
